### PR TITLE
fix complex sampler

### PR DESCRIPTION
**Pull request by fredshone**
just a little debug that was required to run the fac sampler. Not sure why

### CODE REVIEW

**Comment by Theodore-Chatziioannou** [comment]
do you recall what was the error? I had added the `.values` property so that we divide objects of the same type (numpy array).

**Comment by fredshone** [comment]
yes - weights was already an array.

From this block pressumably?

```           
if isinstance(transit_distance, pd.Series) and mode in transit_modes:
    weights = np.where(
        transit_distance > max_walk,
        weights * variables.SMALL_VALUE, # if no alternative is found within the acceptable range, the initial weights will be used
        weights
   )
```

**Comment by Theodore-Chatziioannou** [comment]
ok, so there is a code path that casts weights to arrays and one where they are kept as Series (which I think will crash after your update?). Should we cast to array in any case then?

**Comment by fredshone** [comment]
sure - let me re push

**Review by Theodore-Chatziioannou — APPROVED** [review]

**Pull request merged**
