### PR TITLE
Release v0.3.2

### PR DESCRIPTION
**Pull request by fredshone**
Version bump for JOSS (journal of open source software) release.

- [x] CHANGELOG updated
- [x] Tests added to cover contribution
- [x] Documentation updated

### CODE REVIEW

**Comment by brynpickering** [comment]
Can you push the v0.3.2 tag @fredshone ? Package builds won't run without it

**Comment by brynpickering** [comment]
Another issue: looks like your local repo isn't quite set up right. None of the notebooks can find the `pam` module. I would recommend deleting any empty `pam` directory you now have (a ghostly reminder of the pre `src` world) and remember to a. run `pip install --no-deps -e .` to install the pam jupyter kernel `ipython kernel install --user --name pam` (I think. It's in the docs)

**Comment by brynpickering** [comment]
Blocked by: https://github.com/arup-group/actions-city-modelling-lab/pull/18

**Comment by fredshone** [comment]
> Another issue: looks like your local repo isn't quite set up right. None of the notebooks can find the pam module.

You are right, i have the old pam directory,  but I'd like to know how you knew this???

**Comment by brynpickering** [comment]
> You are right, i have the old pam directory, but I'd like to know how you knew this???

Look behind you.

**Review by brynpickering — APPROVED** [review]

**Pull request merged**
